server:
  port: 8081
  servlet:
    context-path: /auth
spring:
  resources:
    static-locations: classpath:/templates  #访问静态页面
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ump_sso?serverTimezone=Asia/Shanghai
    username: root
    password: 1234abcd
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
#mybaits-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  #实体扫描
  typeAliasesPackage:  com.github.jackieonway.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    field-strategy: 1
    db-column-underline: true
    refresh-mapper: true
    logic-delete-value: 1  #配置逻辑删除字段为1是删除
    logic-not-delete-value: 0 #配置逻辑删除字段为101001是未删除
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector #逻辑删除配置
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用
security:
  oauth2:
    authorization:
      check-token-access: true
logging:
  level:
    com: debug
    org: debug
